SDC_BE_URL = "http://sdc.api.fe.simpledemo.onap.org:30206"
SDC_FE_URL = "http://sdc.api.fe.simpledemo.onap.org:30206"
AAI_URL = "http://aai.api.sparky.simpledemo.onap.org:5000"
SO_URL = "http://so.api.simpledemo.onap.org:5001"
SDNC_URL = "http://sdnc.api.simpledemo.onap.org:5002"
CLAMP_URL   = "http://clamp.api.simpledemo.onap.org:30258"
CDS_URL = "http://cds.api.simpledemo.onap.org:8080"
